regions:
  # - "global" # This is for all global resource types e.g. IAM
  # - "us-east-2"
  # - "us-east-1"
  # - "us-west-1"
  # - "us-west-2"
  # - "af-south-1"
  # - "ap-east-1"
  # - "ap-south-1"
  # - "ap-northeast-3"
  # - "ap-northeast-2"
  # - "ap-southeast-1"
  # - "ap-southeast-2"
  # - "ap-northeast-1"
  # - "ca-central-1"
  # - "cn-north-1"
  # - "cn-northwest-1"
  # - "eu-central-1"
  # - "eu-west-1"
  # - "eu-west-2"
  # - "eu-south-1"
  - "eu-west-3"
    # - "eu-north-1"
    # - "me-south-1"
    # - "sa-east-1"

account-blocklist:
- "999999999999" # production

presets:
  sso:
    filters:
      IAMSAMLProvider:
      - type: "regex"
        value: "AWSSSO_.*_DO_NOT_DELETE"
      IAMRole:
      - type: "glob"
        value: "AWSReservedSSO_*"
      IAMRolePolicyAttachment:
      - type: "glob"
        value: "AWSReservedSSO_*"

accounts:
  930842625961:
    presets:
      - sso

resource-types:
  # don't nuke IAM users
  targets:
  - EC2*
  excludes:
  - IAMGroup
  - IAMGroupPolicy
  - IAMGroupPolicyAttachment
  - IAMInstanceProfile
  - IAMInstanceProfileRole
  - IAMLoginProfile
  - IAMOpenIDConnectProvider
  - IAMPolicy
  - IAMRole
  - IAMRolePolicy
  - IAMRolePolicyAttachment
  - IAMSAMLProvider
  - IAMServerCertificate
  - IAMServiceSpecificCredential
  - IAMUser
  - IAMUserAccessKey
  - IAMUserGroupAttachment
  - IAMUserPolicy
  - IAMUserPolicyAttachment
  - IAMUserSSHPublicKey
  - IAMVirtualMFADevice
