name: Golang CI

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened, synchronize]
  schedule:
  - cron: '15 3 * * 0'

jobs:
  build:
    name: CI Build
    runs-on: ubuntu-22.04
    steps:
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.21'
    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    - name: Install flake8
      run: pip install flake8
    - name: Setup tools
      run: |
        go install golang.org/x/lint/golint@latest
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Check Formatting
      run: |
        if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then
          echo "### Go formatting is off, please execute 'gofmt -w -s .' - see following diff: ###"
          gofmt -s -d .
          exit 1
        fi
        make qa_check_code
    - name: Test Project
      run: |
        make test
    - name: Build Project
      run: |
        make
    - name: Deploy to AWS CloudFormation
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      with:
        name: AwsClean
        template: stack.yaml
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-3
